import { renderMarkdown } from "@/lib/markdown";

/**
 * Product copy, rendered from the Markdown subset in lib/markdown.
 *
 * The HTML handed to dangerouslySetInnerHTML here is generated by our own
 * renderer, which escapes the source before parsing — the author's raw HTML
 * never survives. See lib/markdown.ts for why that matters.
 */
export default function ProductDescription({
  source,
  className = "",
}: {
  source?: string | null;
  className?: string;
}) {
  const html = renderMarkdown(source ?? "");
  if (!html) return null;

  return (
    <div
      className={
        "text-sm text-muted-foreground leading-relaxed " +
        "[&_p]:mb-3 [&_p:last-child]:mb-0 " +
        "[&_h3]:text-foreground [&_h3]:font-medium [&_h3]:text-base [&_h3]:mt-5 [&_h3]:mb-2 " +
        "[&_h4]:text-foreground [&_h4]:font-medium [&_h4]:mt-4 [&_h4]:mb-1.5 " +
        "[&_h5]:text-foreground [&_h5]:font-medium [&_h5]:mt-3 [&_h5]:mb-1 " +
        "[&_ul]:list-disc [&_ul]:pl-5 [&_ul]:mb-3 [&_ul]:space-y-1 " +
        "[&_ol]:list-decimal [&_ol]:pl-5 [&_ol]:mb-3 [&_ol]:space-y-1 " +
        className
      }
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}
